dismiss:
  fields:
    target:
      example: ["my_phone", "my_tablet"]
      selector:
        object:
    data:
      example: '{ "tag": "tagname" }'
      selector:
        object:
    title:
      example: "Title"
      selector:
        text:
          multiline: false
